@url_base=http://localhost:5000 

### Save User
POST {{url_base}}/users
Content-Type: application/json

{
  "name": "Leonen",
  "email": "agui@leonen.com"
}

### List Users
GET {{url_base}}/users
Content-Type: application/json

### Save Transactions
POST {{url_base}}/transactions
Content-Type: application/json

{
  "user_id": 10,
  "amount": 1000.00,
  "type": "withdrawal"
}

###List transactions for user
GET {{url_base}}/transactions/10
Content-Type: application/json

